/*
 * Teoh Ean Zou
 * SWE1804433
 * Tan Tian Lim
 * SWE1804420
 */
package assignment_client;

import static assignment_client.start.user; //username from start
import static assignment_client.start.bar_title; //username from start
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

public class CategoryPage extends javax.swing.JFrame {

    static Socket socket = null;
    static ObjectOutputStream oos = null;
    static ObjectInputStream ois = null;
    int takeonce;
    String page = "Category";
    int category_num;
    start start = new start(); 
    
    public CategoryPage() {
        initComponents();
    }
    
    public CategoryPage(Socket socket, ObjectOutputStream oos, ObjectInputStream ois, int takeonce) {
        initComponents();
        
        this.setTitle(bar_title + ": Client (" + user + ")");
        
        this.socket = socket;
        this.oos=oos;
        this.ois=ois;
        this.takeonce=takeonce; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parcel = new javax.swing.JButton();
        shop = new javax.swing.JButton();
        food = new javax.swing.JButton();
        move = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 400));

        parcel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        parcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/parcel_small.png"))); // NOI18N
        parcel.setText("Parcel Delivery");
        parcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelActionPerformed(evt);
            }
        });

        shop.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        shop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-bag.png"))); // NOI18N
        shop.setText("Shop for Me\n\n\n");
        shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopActionPerformed(evt);
            }
        });

        food.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salad.png"))); // NOI18N
        food.setText("Food Delivery");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });

        move.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/moving.png"))); // NOI18N
        move.setText("House Moving");
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zoom Delivery Service");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parcel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //parcel page
    private void parcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelActionPerformed
        try {
            
            category_num = 0;
            oos.writeObject(category_num); //tell server which button client click
            page = "Parcel";
            oos.writeObject(page); //pass page number
        
            ParcelPage parcel_page = new ParcelPage(socket, oos, ois, 0, takeonce);
            parcel_page.setLocation(this.getX(), this.getY());
            parcel_page.setVisible(true); //pass details to next page
            this.setVisible(false);

        } catch (IOException ex) {start.fail_to_connect();}
       
    }//GEN-LAST:event_parcelActionPerformed
    
    //shopping page
    private void shopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopActionPerformed
        // TODO add your handling code here:
        try {
            
            category_num = 1;
            oos.writeObject(category_num); //tell server which button client click
            page = "ShopMall";
            oos.writeObject(page); //pass page number
            
            ChooseShopMallPage shopmall_page = new ChooseShopMallPage(socket, oos, ois, 1, takeonce);
            shopmall_page.setLocation(this.getX(), this.getY()); //put middle
            shopmall_page.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {start.fail_to_connect();}

    }//GEN-LAST:event_shopActionPerformed
    
    //food page
    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
       try {
           
            category_num = 2;
            oos.writeObject(category_num); //tell server which button client click
            page = "FoodDel";
            oos.writeObject(page); //pass page number
            
            ChooseShopMallPage shopmall_page = new ChooseShopMallPage(socket, oos, ois, 2, takeonce);
            shopmall_page.setLocation(this.getX(), this.getY()); //put middle
            shopmall_page.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {start.fail_to_connect();}    
    }//GEN-LAST:event_foodActionPerformed
    
    //moving page
    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed

        try {
            
            category_num = 3;
            oos.writeObject(category_num); //tell server which button client click
            page = "Moving";
            oos.writeObject(page); //pass page number
            
            MovingPage parcel_page = new MovingPage(socket, oos, ois, 3, takeonce);
            parcel_page.setLocation(this.getX(), this.getY());; //put middle
            parcel_page.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {start.fail_to_connect();}

    }//GEN-LAST:event_moveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton move;
    private javax.swing.JButton parcel;
    private javax.swing.JButton shop;
    // End of variables declaration//GEN-END:variables
}
