/*
 * Teoh Ean Zou
 * SWE1804433
 * Tan Tian Lim
 * SWE1804420
 */
package assignment_client;

import static assignment_client.start.bar_title;
import static assignment_client.start.user;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.Integer.parseInt;
import java.net.Socket;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ChooseFoodPage extends javax.swing.JFrame {

    /**
     * Creates new form ChooseFoodPage
     */
    static Socket socket = null;
    static ObjectOutputStream oos = null;
    static ObjectInputStream ois = null;
    String[] selected_item;
    int pass_choose, takeonce;
    String page = "ShopFood";
    start start = new start(); 
            
    public ChooseFoodPage() {
        initComponents();
    }
    
    JComboBox[] qty_box = new JComboBox[3];
    String[] num = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};
    JLabel[] food_name = new JLabel[3];
    JLabel[] food_price = new JLabel[3];
    String[][] menu = new String[3][2];
    public ChooseFoodPage(Socket socket, ObjectOutputStream oos, ObjectInputStream ois, int pass_choose, 
                           String[] selected_item, int takeonce) throws IOException, ClassNotFoundException {
       initComponents();
       this.setTitle(bar_title + ": Client (" + user + ")");

       this.socket = socket;
       this.oos=oos;
       this.ois=ois;
       this.pass_choose = pass_choose;
       this.takeonce=takeonce;
       
       this.selected_item = new String[2];
        for (int i=0; i<2; i++) //got pickup and shop
            this.selected_item[i] = selected_item[i];
       
       if (takeonce==0)
        {
            ois = new ObjectInputStream(socket.getInputStream());
            this.ois = ois;
            
            takeonce=1;
            this.takeonce = takeonce;
        }
       
       //get menu based on passed shop previously
       for (int i=0; i<3; i++)
       {
            for (int j=0; j<2; j++)
            {
                menu[i][j] = (String) ois.readObject();
                
                if (j==0)
                {
                    food_name[i] = new JLabel(menu[i][j]);
                    food_panel.add(food_name[i]); 
                }
                else
                {
                    food_price[i] = new JLabel("RM " + menu[i][j]);
                    price_panel.add(food_price[i]);
                }
            }
            
            food_panel.validate();
            price_panel.validate();
            
            qty_box[i] = new JComboBox(num);
            qty_panel.add(qty_box[i]);
            qty_panel.validate();
       }

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        food_panel = new javax.swing.JPanel();
        price_panel = new javax.swing.JPanel();
        qty_panel = new javax.swing.JPanel();
        cart = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Food List");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        food_panel.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        price_panel.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        qty_panel.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(food_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(price_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(qty_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(food_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(price_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qty_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        cart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trolley.png"))); // NOI18N
        cart.setText("Cart");
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Food Item");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cart)
                            .addComponent(next)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            oos.writeObject("Back");
            page = "ShopMall";
            oos.writeObject(page); //pass page number
            
            ChooseShopMallPage shopmall_page = new ChooseShopMallPage(socket, oos, ois, pass_choose, takeonce);
            shopmall_page.setLocation(this.getX(), this.getY());
            shopmall_page.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {start.fail_to_connect();}
        
        
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try 
        {
            get_item();
            
            if (cart_num == 0)
            {
                JOptionPane.showMessageDialog(null, "You did not enter anything, please add some items to proceed",
                                            "Warning",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                oos.writeObject("next");
                
                oos.writeObject(cart_num); //pass the total num of items
            
                for (int i=0; i<cart_num; i++)
                {
                    for (int j=0; j<2; j++)
                    {
                        oos.writeObject(items_in_cart[i][j]);
                    }
                }

                page = "SummaryShop";
                oos.writeObject(page); //pass page number

                SummaryShopPage summaryshop = new SummaryShopPage(socket, oos, ois, pass_choose, selected_item, 
                                                                    cart_num, items_in_cart, price_in_cart, takeonce);
                summaryshop.setLocation(this.getX(), this.getY());
                summaryshop.setVisible(true);
                this.setVisible(false);
            }

        } catch (IOException | ClassNotFoundException ex) {start.fail_to_connect();}
    }//GEN-LAST:event_nextActionPerformed

    int cart_num = 0;
    String[][] items_in_cart = new String[3][2];
    String[] price_in_cart = new String[3];
    String cart_dialog;
    int total;
    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        
        get_item();
        
        if (cart_num == 0)
        {
            JOptionPane.showMessageDialog(null, "Your cart is empty, please add something",
                    "Your Cart (" + total + " item(s))", JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            cart_dialog = ""; //reset
            
            for (int i=0; i<cart_num; i++)
            {
                cart_dialog = cart_dialog + (i+1) + ". ";
                for (int j=0; j<2; j++)
                {
                    cart_dialog = cart_dialog + items_in_cart[i][j] + "        ";
                }
                cart_dialog = cart_dialog + price_in_cart[i] + "\n";
            }
            
            JOptionPane.showMessageDialog(null, cart_dialog,
                    "Your Cart (" + total + " item(s))", JOptionPane.PLAIN_MESSAGE);
        }
      
    }//GEN-LAST:event_cartActionPerformed

    public void get_item()
    {
        total = 0; 
        cart_num = 0; //everytime click in will reset and recount
        int row = 0; 
        //determine did user select something
        for (int i=0; i<3; i++)
        {
            String x;
            x = qty_box[i].getSelectedItem().toString();
            if (parseInt(x) != 0) //if not zero then add to cart
            {
                items_in_cart[row][0] = food_name[i].getText(); //name
                items_in_cart[row][1] = x; //quantity
                price_in_cart[row] = food_price[i].getText(); //price
                row++;
                cart_num++;
            }
            total = total + parseInt(x);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseFoodPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseFoodPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseFoodPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseFoodPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseFoodPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cart;
    private javax.swing.JPanel food_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JPanel price_panel;
    private javax.swing.JPanel qty_panel;
    // End of variables declaration//GEN-END:variables
}
