/*
 * Teoh Ean Zou
 * SWE1804433
 * Tan Tian Lim
 * SWE1804420
 */

package assignment_client;

import static assignment_client.start.bar_title;
import static assignment_client.start.user;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

public class MovingPage extends javax.swing.JFrame {

    static Socket socket = null;
    static ObjectOutputStream oos = null;
    static ObjectInputStream ois = null;
    int pass_choose, takeonce; 
    String page = "Moving";
    start start = new start(); 
    
    public MovingPage() {
        initComponents();
    }
    
    public MovingPage(Socket socket, ObjectOutputStream oos, ObjectInputStream ois, int pass_choose, int takeonce) {
        initComponents();
        this.setTitle(bar_title + ": Client (" + user + ")");
        
        this.socket = socket;
        this.oos = oos;
        this.ois = ois;
        this.takeonce = takeonce;
        this.pass_choose = pass_choose;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num_worker_label = new javax.swing.JLabel();
        num_vehicle_label = new javax.swing.JLabel();
        num_vehicle = new javax.swing.JComboBox<>();
        num_worker = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        origin_label = new javax.swing.JLabel();
        dropoff_label = new javax.swing.JLabel();
        origin = new javax.swing.JComboBox<>();
        dropoff = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        vehicle = new javax.swing.JComboBox<>();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 330));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 330));

        num_worker_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num_worker_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num_worker_label.setText("Number of workers:");

        num_vehicle_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num_vehicle_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num_vehicle_label.setText("Number of Vehicles: ");

        num_vehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num_vehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        num_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_vehicleActionPerformed(evt);
            }
        });

        num_worker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num_worker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        num_worker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_workerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zoom House Moving");

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        origin_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        origin_label.setText("Origin Location:");

        dropoff_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropoff_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dropoff_label.setText("Dropoff Location:");

        origin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xiamen University Malaysia", "The Olive", "Sunway University", "Taylor University" }));

        dropoff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropoff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xiamen University Malaysia", "The Olive", "Sunway University", "Taylor University" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vehicle Type: ");

        vehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pickup Truck", "Van", "1-Ton Lorry", "3-Ton Lorry", "5-Ton Lorry" }));

        next.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dropoff_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(origin_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(origin, 0, 205, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(dropoff, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vehicle, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num_vehicle_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(num_worker_label, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addGap(31, 31, 31))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num_worker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num_vehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 73, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_worker_label)
                    .addComponent(origin_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_worker, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_vehicle_label)
                    .addComponent(dropoff_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(next)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void num_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_vehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_vehicleActionPerformed

    private void num_workerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_workerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_workerActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try {
            
            oos.writeObject("Back");
            page = "Category";
            oos.writeObject(page); //pass page number
            
            CategoryPage category_page = new CategoryPage(socket, oos, ois, takeonce);
            category_page.setLocation(this.getX(), this.getY());
            category_page.setVisible(true);
            this.setVisible(false);
        
        } catch (IOException ex) {start.fail_to_connect();}
        
    }//GEN-LAST:event_backActionPerformed
     
    String[] selected_item = new String [5];
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try 
        {
            oos.writeObject("next");
            //oos = new ObjectOutputStream(socket.getOutputStream());
            
            selected_item[0] = (String) origin.getSelectedItem(); //record
            selected_item[1] = (String) dropoff.getSelectedItem();
            selected_item[2] = (String) vehicle.getSelectedItem();
            selected_item[3] = (String) num_worker.getSelectedItem();
            selected_item[4] = (String) num_vehicle.getSelectedItem();
            
            for (int i=0; i<5; i++)
                oos.writeObject(selected_item[i]); //pass all items selected
        
            check_duplication();
        } catch (IOException ex) {} catch (ClassNotFoundException ex) {start.fail_to_connect();}
    }//GEN-LAST:event_nextActionPerformed
    
    private void check_duplication() throws IOException, ClassNotFoundException
     {
        int error;
        if (takeonce==0)
            ois = new ObjectInputStream(socket.getInputStream());
        takeonce = 1; //never get input stream again
        error = (int) ois.readObject();
        takeonce=1;
        
        if (error == 1)
        {
            JOptionPane.showMessageDialog(null, "Pickup location and Dropoff location are the same, please change",
                                            "Warning",JOptionPane.WARNING_MESSAGE);
            page = "Moving";
            oos.writeObject(page);
        }
        else
        {
            page = "Summary";
            oos.writeObject(page); //pass page number
            SummaryPage summary_page = new SummaryPage(socket, oos, ois, pass_choose, selected_item, takeonce);
            summary_page.setLocation(this.getX(), this.getY());
            summary_page.setVisible(true); 
            this.setVisible(false);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> dropoff;
    private javax.swing.JLabel dropoff_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> num_vehicle;
    private javax.swing.JLabel num_vehicle_label;
    private javax.swing.JComboBox<String> num_worker;
    private javax.swing.JLabel num_worker_label;
    private javax.swing.JComboBox<String> origin;
    private javax.swing.JLabel origin_label;
    private javax.swing.JComboBox<String> vehicle;
    // End of variables declaration//GEN-END:variables
}
