/*
 * Teoh Ean Zou
 * SWE1804433
 * Tan Tian Lim
 * SWE1804420
 */

package assignment_client;

import static assignment_client.start.bar_title;
import static assignment_client.start.user;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JLabel;

public class SummaryShopPage extends javax.swing.JFrame {

    /**
     * Creates new form SummaryShopPage
     */
    
    static Socket socket = null;
    static ObjectOutputStream oos = null;
    static ObjectInputStream ois = null;
    int pass_choose, takeonce; 
    int total_item;
    String[][] items_in_cart;
    String[] price_in_cart;
    String[] selected_item;
    String page = "SummaryShop";
    int fee_travel, fee_total;
    start start = new start(); 
    
    public SummaryShopPage() {
        initComponents();
    }
    
    public SummaryShopPage (Socket socket, ObjectOutputStream oos, ObjectInputStream ois, int pass_choose, 
            String[] selected_item, int total_item, String items_in_cart[][], String[] price_in_cart, int takeonce) throws IOException, ClassNotFoundException {
        initComponents();
        this.setTitle(bar_title + ": Client (" + user + ")");
        
        this.socket = socket;
        this.oos=oos;
        this.ois=ois;
        this.pass_choose = pass_choose;
        this.takeonce=takeonce;
        this.total_item = total_item;
        
        this.selected_item = new String[2];
        for (int i=0; i<2; i++) //got pickup and shop
            this.selected_item[i] = selected_item[i];
        
        this.items_in_cart = new String[total_item][2];
        for (int i=0; i<total_item; i++)
        {
            for (int j=0; j<2; j++)
            {
                this.items_in_cart[i][j] = items_in_cart[i][j];
            }
        }
        
        this.price_in_cart = new String[total_item];
        for (int i=0; i<total_item; i++)
        {
            this.price_in_cart[i] = price_in_cart[i];
        }
        
        shop.setText(selected_item[0]);
        loc.setText(selected_item[1]);
        
        if (takeonce==0)
        {
            ois = new ObjectInputStream(socket.getInputStream());
            this.ois = ois;
            
            takeonce=1;
            this.takeonce = takeonce;
        }
        
        fee_travel = (int) ois.readObject();
        fee.setText("RM " + String.valueOf(fee_travel));
        
        if (pass_choose == 2) //food
        {
            notice.setText(""); //empty that line cause no need
            
            fee_total = (int) ois.readObject();
            ttl_fee.setText("RM " + String.valueOf(fee_total));
        }
        else //shopping
        {
            ttl_fee.setText("RM " + String.valueOf(fee_travel));
        }

        add_content();
    }
    
    public void add_content()
    {
        new Thread()
        {
            public void run()
            {
                JLabel[][] item = new JLabel[total_item][2];
                JLabel[] item_price = new JLabel[total_item];

                for (int i=0; i<total_item; i++)
                {
                    item[i][0] = new JLabel(items_in_cart[i][0]); //item name
                    item_panel.add(item[i][0]);
                    item_panel.validate();

                    item[i][1] = new JLabel(items_in_cart[i][1]); //qty
                    qty_panel.add(item[i][1]);
                    qty_panel.validate();  
                    
                    item_price[i] = new JLabel(price_in_cart[i]); //price
                    price_panel.add(item_price[i]);
                    price_panel.validate(); 
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        item_panel = new javax.swing.JPanel();
        qty_panel = new javax.swing.JPanel();
        price_panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        notice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shop = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttl_fee = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        item_panel.setLayout(new java.awt.GridLayout(20, 1, 0, 10));

        qty_panel.setLayout(new java.awt.GridLayout(20, 1, 0, 10));

        price_panel.setLayout(new java.awt.GridLayout(20, 1, 0, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(price_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(qty_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qty_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(price_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        title.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Order Summary");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Item Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Quantity");

        notice.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        notice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notice.setText("*Item prices will be known when items are delivered");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Delivery Fee");

        fee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fee.setText("RM 10");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Selected Shop");

        shop.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        shop.setText("Sunway Pyramid");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Dropoff location");

        loc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loc.setText("Xiamen University Malaysia");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Total Fee ");

        ttl_fee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ttl_fee.setText("RM 10");

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setText("Price (per item)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shop)
                                    .addComponent(loc))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fee, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(ttl_fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shop)
                    .addComponent(jLabel1)
                    .addComponent(fee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loc)
                        .addComponent(jLabel4)
                        .addComponent(ttl_fee))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         try {                                     
            // TODO add your handling code here:
            String page = "Delivery";
            
            oos.writeObject(page);
            DeliveringPage delivery_page = new DeliveringPage(socket, oos, ois, pass_choose, takeonce);
            delivery_page.setLocation(this.getX(), this.getY());
            delivery_page.setVisible(true); //pass details to next page
            this.setVisible(false);
            
        } catch (IOException | ClassNotFoundException ex) {start.fail_to_connect();}
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            // TODO add your handling code here:
            if (pass_choose == 1)
            {
                page = "ShopItem";
                oos.writeObject(page); //pass page number

                ShopItemPage shopitem_page = new ShopItemPage(socket, oos, ois, pass_choose, selected_item, takeonce);
                shopitem_page.setLocation(this.getX(), this.getY());
                shopitem_page.setVisible(true); 
                this.setVisible(false);
            }
            else
            {
                page = "ShopFood";
                oos.writeObject(page); //pass page number
                
                ChooseFoodPage choosefood_page = new ChooseFoodPage(socket, oos, ois, pass_choose, selected_item, takeonce);
                choosefood_page.setLocation(this.getX(), this.getY());
                choosefood_page.setVisible(true); 
                this.setVisible(false);
            }
            
        } catch (IOException | ClassNotFoundException ex) {start.fail_to_connect();}
    }//GEN-LAST:event_backActionPerformed

    JLabel[][] item = new JLabel[total_item][2];
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryShopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryShopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryShopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryShopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummaryShopPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel fee;
    private javax.swing.JPanel item_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loc;
    private javax.swing.JButton next;
    private javax.swing.JLabel notice;
    private javax.swing.JLabel price;
    private javax.swing.JPanel price_panel;
    private javax.swing.JPanel qty_panel;
    private javax.swing.JLabel shop;
    private javax.swing.JLabel title;
    private javax.swing.JLabel ttl_fee;
    // End of variables declaration//GEN-END:variables
}
