/*
 * Teoh Ean Zou
 * SWE1804433
 * Tan Tian Lim
 * SWE1804420
 */

package assignment_client;

import static assignment_client.start.bar_title;
import static assignment_client.start.user;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

public class SummaryPage extends javax.swing.JFrame {

    static Socket socket = null;
    static ObjectOutputStream oos = null;
    static ObjectInputStream ois = null;
    String[] selected_item;
    int pass_choose, takeonce;
    String page = "Summary";
    start start = new start(); 
    
    public SummaryPage() {
        initComponents();
    }
    
    public SummaryPage(Socket socket, ObjectOutputStream oos, ObjectInputStream ois, int pass_choose, String[] selected_item, int takeonce) throws IOException, ClassNotFoundException {
        initComponents();
        this.setTitle(bar_title + ": Client (" + user + ")");
        
        this.socket = socket;
        this.oos=oos;
        this.ois=ois;
        this.pass_choose = pass_choose;
        this.takeonce=takeonce;

        pickup.setText(selected_item[0]);
        dropoff.setText(selected_item[1]);
        vehicle.setText(selected_item[2]);

        int fee_travel, fee_vehicle, fee_num_vehicle, fee_num_worker, fee_total;
        
        fee_travel = (int) ois.readObject();
        t_fee.setText("RM " + String.valueOf(fee_travel));
        
        fee_vehicle = (int) ois.readObject();
        v_fee.setText("RM " + String.valueOf(fee_vehicle));
        
        if (pass_choose == 3)
        {
            vehicle.setText(selected_item[4] + " " + selected_item[2]); //change the text to put quantity
            po_location.setText("Origin Location");
            fee_num_vehicle = (int) ois.readObject();
            fee_num_worker = (int) ois.readObject();
            extra_v_label.setText("Extra Vehicle Fee"); //add words to label
            extra_v.setText("RM " + String.valueOf(fee_num_vehicle));
            extra_w_label.setText("Extra Worker Fee");
            extra_w.setText("RM " + String.valueOf(fee_num_worker));
        }
        
        if (pass_choose == 0) //if choose parcel category
            move_panel(); //move normal panel to the middle

        fee_total = (int) ois.readObject();
        total_fee.setText("RM " + String.valueOf(fee_total));
    }
    
     public void move_panel()
     { 
         new Thread()
         {
             int counter = 2;
                public void run()
                {
                    while (counter > 0)
                    {
                        normal_panel.setLocation(normal_panel.getLocation().x+100, normal_panel.getLocation().y); 
                        try
                        {
                            Thread.sleep(50); //1 second delay
                        } catch (Exception e){}
                        counter--;
                    }
                }
         }.start();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        po_location = new javax.swing.JLabel();
        total_fee = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pickup = new javax.swing.JLabel();
        dropoff = new javax.swing.JLabel();
        vehicle = new javax.swing.JLabel();
        moving_panel = new javax.swing.JPanel();
        extra_v_label = new javax.swing.JLabel();
        extra_w_label = new javax.swing.JLabel();
        extra_v = new javax.swing.JLabel();
        extra_w = new javax.swing.JLabel();
        normal_panel = new javax.swing.JPanel();
        v_fee = new javax.swing.JLabel();
        t_fee = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        extra_label = new javax.swing.JLabel();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 350));

        title.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Order Summary");

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Total fee");

        po_location.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        po_location.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        po_location.setText("Pickup Location");

        total_fee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        total_fee.setText("RM 20");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Dropoff Location");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setText("------------------------------------------------------------------------------------------");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Vehicle Type");

        pickup.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pickup.setText("Xiamen University Malaysia");

        dropoff.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dropoff.setText("Xiamen University Malaysia");

        vehicle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        vehicle.setText("Motorcycle");

        extra_v_label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        extra_v_label.setMaximumSize(new java.awt.Dimension(52, 14));
        extra_v_label.setMinimumSize(new java.awt.Dimension(52, 14));
        extra_v_label.setPreferredSize(new java.awt.Dimension(52, 14));

        extra_w_label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        extra_w_label.setMaximumSize(new java.awt.Dimension(52, 14));
        extra_w_label.setMinimumSize(new java.awt.Dimension(52, 14));
        extra_w_label.setPreferredSize(new java.awt.Dimension(52, 14));

        extra_v.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        extra_v.setMaximumSize(new java.awt.Dimension(9, 14));
        extra_v.setMinimumSize(new java.awt.Dimension(9, 14));
        extra_v.setPreferredSize(new java.awt.Dimension(9, 14));

        extra_w.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        extra_w.setMaximumSize(new java.awt.Dimension(9, 14));
        extra_w.setMinimumSize(new java.awt.Dimension(9, 14));
        extra_w.setPreferredSize(new java.awt.Dimension(9, 14));

        javax.swing.GroupLayout moving_panelLayout = new javax.swing.GroupLayout(moving_panel);
        moving_panel.setLayout(moving_panelLayout);
        moving_panelLayout.setHorizontalGroup(
            moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moving_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extra_v_label, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(extra_w_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extra_w, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(extra_v, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        moving_panelLayout.setVerticalGroup(
            moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moving_panelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extra_v, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra_v_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moving_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extra_w, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extra_w_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        v_fee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        v_fee.setText("RM 10");

        t_fee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        t_fee.setText("RM 10");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Travel Fee");

        extra_label.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        extra_label.setText("Vehicle Fee");

        javax.swing.GroupLayout normal_panelLayout = new javax.swing.GroupLayout(normal_panel);
        normal_panel.setLayout(normal_panelLayout);
        normal_panelLayout.setHorizontalGroup(
            normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, normal_panelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extra_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(v_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        normal_panelLayout.setVerticalGroup(
            normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, normal_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_fee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(normal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extra_label)
                    .addComponent(v_fee))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(normal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(23, 23, 23)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moving_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(po_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pickup, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(total_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(po_location)
                    .addComponent(pickup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropoff)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicle)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moving_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normal_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(total_fee))
                .addGap(18, 18, 18))
        );

        next.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(next)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        if (pass_choose == 0)
        {
            String page = "Parcel";
            try {
                
                oos.writeObject(page); //pass page number
                
                ParcelPage parcel_page = new ParcelPage(socket, oos, ois, pass_choose, takeonce);
                parcel_page.setLocation(this.getX(), this.getY());
                parcel_page.setVisible(true); //pass details to next page
                this.setVisible(false);
                
            } catch (IOException ex) {start.fail_to_connect();}
            
        }
        else if (pass_choose == 3)
        {
            String page = "Moving";
            try {
                
                oos.writeObject(page); //pass page number
                
                MovingPage parcel_page = new MovingPage(socket, oos, ois, pass_choose, takeonce);
                parcel_page.setLocation(this.getX(), this.getY());
                parcel_page.setVisible(true);
                this.setVisible(false);
                
            } catch (IOException ex) {start.fail_to_connect();}
            
        }
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try {                                     
            // TODO add your handling code here:
            String page = "Delivery";
            
            oos.writeObject(page);
            DeliveringPage delivery_page = new DeliveringPage(socket, oos, ois, pass_choose, takeonce);
            delivery_page.setLocation(this.getX(), this.getY());
            delivery_page.setVisible(true); //pass details to next page
            this.setVisible(false);
            
        } catch (IOException | ClassNotFoundException ex) {start.fail_to_connect();}
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */    
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummaryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel dropoff;
    private javax.swing.JLabel extra_label;
    private javax.swing.JLabel extra_v;
    private javax.swing.JLabel extra_v_label;
    private javax.swing.JLabel extra_w;
    private javax.swing.JLabel extra_w_label;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel moving_panel;
    private javax.swing.JButton next;
    private javax.swing.JPanel normal_panel;
    private javax.swing.JLabel pickup;
    private javax.swing.JLabel po_location;
    private javax.swing.JLabel t_fee;
    private javax.swing.JLabel title;
    private javax.swing.JLabel total_fee;
    private javax.swing.JLabel v_fee;
    private javax.swing.JLabel vehicle;
    // End of variables declaration//GEN-END:variables
}
